version: '3.4'

services:
  accountservice:
    image: solucaoi9/accountservice
    build:
      context: ./Services/AccountService
      dockerfile: Dockerfile
    ports:
    - "8081:80"
    networks:
      store2020network:
        ipv4_address: 172.19.10.101

  inventoryservice:
    image: solucaoi9/inventoryservice
    build:
      context: ./Services/InventoryService
      dockerfile: Dockerfile
    ports:
    - "8082:80"
    networks:
      store2020network:
        ipv4_address: 172.19.10.102

  shoppingcartservice:
    image: solucaoi9/shoppingcartservice
    build:
      context: ./Services/ShoppingCartService
      dockerfile: Dockerfile
    ports:
    - "8083:80"
    networks:
      store2020network:
        ipv4_address: 172.19.10.103

  store2020:
    image: solucaoi9/store2020
    depends_on:
    - accountservice
    - inventoryservice
    - shoppingcartservice
    environment:
      ACCOUNT_SERVICE_API_BASE: http://172.19.10.101/api
      INVENTORY_SERVICE_API_BASE: http://172.19.10.102/api
      SHOPPING_SERVICE_API_BASE: http://172.19.10.103/api
    build:
      context: ./Store2020
      dockerfile: Dockerfile
    ports:
    - "8000:80"
    networks:
      store2020network:
        ipv4_address: 172.19.10.100

networks:
  store2020network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16